server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
#      com.mysql.jdbc.Driver
      url: jdbc:mysql:///leyou?characterEncoding=UTF-8
      username: root
      password: root
  rabbitmq:
      host: 192.168.157.129
      username: admin
      password: admin
      virtual-host: /leyou
      template:
            retry:
              enabled: true
              initial-interval: 10000ms
              max-interval: 80000ms
              multiplier: 2
      publisher-confirms: true
#myBatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #输出sql日志
  mapper-locations: classpath*:mapper/**Mapper.xml     #.xml目录
  type-aliases-package: com.leyou.item.mapper
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1